import { DynamicsAction } from '#types/global';
import {
  Tag as TagIcon,
  CleaningServices as CleanIcon,
  Link as LinkIcon,
  Public as PublicIcon,
  Sync as SyncIcon,
  RefreshOutlined as RefreshIcon,
  Search as SearchIcon,
  Add as AddIcon,
  List as ListIcon,
  Security as SecurityIcon,
  AccountTree as ProjectIcon,
  Email as EmailIcon,
  Home as HomeIcon,
  ManageSearch as SearchPlusIcon,
  PhoneAndroid as MobileIcon,
  History as HistoryIcon,
  BugReport as BugIcon,
  Code as CodeIcon,
  Block as BanIcon,
  Rule as RuleIcon,
  DarkMode as DarkModeIcon,
  PushPin as PinIcon,
  TableChart as TableChartIcon,
  AutoFixHigh as WizardIcon,
  Compare as CompareIcon,
  Tune as TuneIcon,
  Work as WorkIcon,
  Speed as SpeedIcon,
  FlagCircle as FlagIcon,
  AccountTree as WorkflowIcon,
  // Additional distinctive icons
  Badge as BadgeIcon,
  Layers as LayersIcon,
  Edit as EditIcon,
  Build as BuildIcon,
  MonitorHeart as MonitorIcon,
} from '@mui/icons-material';

export interface ActionConfig {
  id: DynamicsAction;
  label: string;
  icon: React.ComponentType;
  tooltip: string;
  category?: 'common' | 'advanced';
  priority?: number;
  // Optional short label and short icon (emoji or short text) for compact UIs like popup
  shortLabel?: string;
  shortIcon?: string;
}

export const formActions: ActionConfig[] = [
  {
    id: 'form:show-logical-names',
    label: 'Logical Names',
    icon: TagIcon,
    tooltip: 'Show logical names for all fields and tabs on the form',
    category: 'common',
    shortLabel: 'Logical',
    shortIcon: '🏷️',
  },
  {
    id: 'form:clear-logical-names',
    label: 'Clear Names',
    icon: CleanIcon,
    tooltip: 'Hide logical names and restore original field labels',
    category: 'common',
    shortLabel: 'Clear',
    shortIcon: '🧹',
  },
  {
    id: 'form:god-mode',
    label: 'God Mode',
    icon: WizardIcon,
    tooltip: 'Make all fields visible and editable regardless of security roles',
    category: 'common',
    shortLabel: 'God Mode',
    shortIcon: '⚡',
  },
  {
    id: 'form:changed-fields',
    label: 'Changed Fields',
    icon: CompareIcon,
    tooltip: 'Highlight fields that have been modified on the current form',
    category: 'common',
    shortLabel: 'Changed Fields',
    shortIcon: '🔄',
  },
  {
    id: 'form:record-url',
    label: 'Record URL',
    icon: LinkIcon,
    tooltip: 'Copy the current record URL to clipboard',
    category: 'common',
    shortLabel: 'URL',
    shortIcon: '🔗',
  },
  {
    id: 'form:record-id',
    label: 'Record ID',
    icon: BadgeIcon,
    tooltip: 'Copy the current record GUID to clipboard',
    category: 'common',
    shortLabel: 'ID',
    shortIcon: '🆔',
  },
  {
    id: 'form:open-web-api',
    label: 'Web API',
    icon: PublicIcon,
    tooltip: 'Open Web API endpoint for this record in a new tab',
    category: 'common',
    shortLabel: 'API',
    shortIcon: '🌐',
  },
  {
    id: 'form:refresh-subgrids',
    label: 'Refresh Subgrids',
    icon: SyncIcon,
    tooltip: 'Refresh all subgrids on the current form',
    category: 'common',
    shortLabel: 'Refresh Subgrid',
    shortIcon: '🔃',
  },
  {
    id: 'form:show-optionset-values',
    label: 'OptionSet Values',
    icon: TuneIcon,
    tooltip: 'View all option set values and their numeric codes',
    category: 'advanced',
    shortLabel: 'OptionSet',
    shortIcon: '⚙️',
  },
  {
    id: 'form:clone-record',
    label: 'Clone Record',
    icon: LayersIcon,
    tooltip: 'Create a duplicate of the current record with all field values',
    category: 'common',
    shortLabel: 'Clone',
    shortIcon: '📄',
  },
  {
    id: 'form:refresh-autosave-off',
    label: 'Refresh Without Save',
    icon: RefreshIcon,
    tooltip: 'Refresh the form without auto-saving changes',
    category: 'advanced',
    shortLabel: 'Refresh',
    shortIcon: '🔃',
  },
  {
    id: 'form:all-fields',
    label: 'Show All Fields',
    icon: TableChartIcon,
    tooltip: 'View all fields and their values in a searchable table',
    category: 'common',
    shortLabel: 'All Fields',
    shortIcon: '📊',
  },
  {
    id: 'form:open-editor',
    label: 'Open Form Editor',
    icon: EditIcon,
    tooltip: 'Open the form editor to modify the form layout',
    category: 'advanced',
    shortLabel: 'Form Edit',
    shortIcon: '✏️',
  },
  {
    id: 'form:table-processes',
    label: 'Table Processes',
    icon: WorkflowIcon,
    tooltip:
      'View workflows, business rules, business process flows, custom APIs, and actions for this entity',
    category: 'advanced',
    shortLabel: 'Processes',
    shortIcon: '🔧',
  },
];

export const debuggingActions: ActionConfig[] = [
  {
    id: 'debugging:forms-monitor',
    label: 'Forms Monitor',
    icon: MonitorIcon,
    tooltip: 'Monitor form events and script executions in real-time',
    category: 'common',
    shortLabel: 'Form Monitor',
    shortIcon: '📡',
  },
  {
    id: 'debugging:ribbon-debugger',
    label: 'Command Checker',
    icon: BugIcon,
    tooltip: 'Debug ribbon commands and check their availability rules',
    category: 'common',
    shortLabel: 'Command Checker',
    shortIcon: '🐛',
  },
  {
    id: 'debugging:perf-center',
    label: 'Perf Center',
    icon: SpeedIcon,
    tooltip: 'Analyze form performance and identify slow operations',
    category: 'common',
    shortLabel: 'Perf Center',
    shortIcon: '🚀',
  },
  {
    id: 'debugging:disable-form-handlers',
    label: 'Disable Form Handlers',
    icon: BanIcon,
    tooltip: 'Temporarily disable all form event handlers for debugging',
    category: 'advanced',
    shortLabel: 'Disable Form Handler',
    shortIcon: '🚫',
  },
  {
    id: 'debugging:disable-business-rules',
    label: 'Disable Business Rules',
    icon: RuleIcon,
    tooltip: 'Temporarily disable all business rules on the current form',
    category: 'advanced',
    shortLabel: 'Disable Bus. Rules',
    shortIcon: '📋',
  },
  {
    id: 'debugging:disable-form-libraries',
    label: 'Disable Form Libraries',
    icon: CodeIcon,
    tooltip: 'Temporarily disable all form JavaScript libraries',
    category: 'advanced',
    shortLabel: 'Disable Libs',
    shortIcon: '📚',
  },
  {
    id: 'debugging:enable-dark-mode',
    label: 'Enable Dark Mode',
    icon: DarkModeIcon,
    tooltip: 'Enable dark mode theme for Dynamics 365 interface',
    category: 'common',
    shortLabel: 'Dark',
    shortIcon: '🌙',
  },
  {
    id: 'debugging:clear-flags',
    label: 'Clear Flags',
    icon: FlagIcon,
    tooltip: 'Clear all debugging flags and restore normal behavior',
    category: 'advanced',
    shortLabel: 'Clear Flags',
    shortIcon: '🧽',
  },
];

export const navigationActions: ActionConfig[] = [
  {
    id: 'navigation:open-record-by-id',
    label: 'Open by ID',
    icon: SearchIcon,
    tooltip: 'Open a specific record by entering its GUID',
    category: 'common',
    shortLabel: 'Id',
    shortIcon: '🔍',
  },
  {
    id: 'navigation:new-record',
    label: 'New Record',
    icon: AddIcon,
    tooltip: 'Create a new record by selecting entity type',
    category: 'common',
    shortLabel: 'New',
    shortIcon: '➕',
  },
  {
    id: 'navigation:open-list',
    label: 'Open List',
    icon: ListIcon,
    tooltip: 'Navigate to a list view for any entity',
    category: 'common',
    shortLabel: 'List',
    shortIcon: '📝',
  },
  {
    id: 'navigation:open-security',
    label: 'Security',
    icon: SecurityIcon,
    tooltip: 'Access security roles and permissions settings',
    category: 'advanced',
    shortLabel: 'Security',
    shortIcon: '🔒',
  },
  {
    id: 'navigation:open-system-jobs',
    label: 'System Jobs',
    icon: WorkIcon,
    tooltip: 'View and monitor system jobs and workflows',
    category: 'common',
    shortLabel: 'Sys Jobs',
    shortIcon: '💼',
  },
  {
    id: 'navigation:open-solutions',
    label: 'Solutions',
    icon: BuildIcon,
    tooltip: 'Access solution management and customizations',
    category: 'common',
    shortLabel: 'Solutions',
    shortIcon: '📦',
  },
  {
    id: 'navigation:open-processes',
    label: 'Processes',
    icon: ProjectIcon,
    tooltip: 'Manage business processes and workflows',
    category: 'advanced',
    shortLabel: 'Process',
    shortIcon: '🔀',
  },
  {
    id: 'navigation:open-mailboxes',
    label: 'Mailboxes',
    icon: EmailIcon,
    tooltip: 'Configure email settings and mailbox status',
    category: 'advanced',
    shortLabel: 'Mailboxes',
    shortIcon: '✉️',
  },
  {
    id: 'navigation:open-main',
    label: 'Home',
    icon: HomeIcon,
    tooltip: 'Navigate to the main Dynamics 365 homepage',
    category: 'common',
    shortLabel: 'Home',
    shortIcon: '🏠',
  },
  {
    id: 'navigation:open-advanced-find',
    label: 'Advanced Find',
    icon: SearchPlusIcon,
    tooltip: 'Open advanced search and query builder',
    category: 'common',
    shortLabel: 'Adv Find',
    shortIcon: '🔎',
  },
  {
    id: 'navigation:open-mobile-client',
    label: 'Mobile',
    icon: MobileIcon,
    tooltip: 'Access the mobile client interface',
    category: 'advanced',
    shortLabel: 'Mobile',
    shortIcon: '📱',
  },
  {
    id: 'navigation:open-solutions-history',
    label: 'Solutions History',
    icon: HistoryIcon,
    tooltip: 'View history of solution imports and changes',
    category: 'advanced',
    shortLabel: 'Solution Hist',
    shortIcon: '🕒',
  },
  {
    id: 'navigation:pin-to-side-panel',
    label: 'Pin to Side Panel',
    icon: PinIcon,
    tooltip: 'Pin the current page to the side navigation panel',
    category: 'advanced',
    shortLabel: 'Pin',
    shortIcon: '📌',
  },
];
