# Manual Build and Test Workflow
# This workflow allows manual building and testing of the extension
# Use the 'Release' workflow for automated releases with proper tagging

name: Manual Build

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests before building'
        type: boolean
        default: true
      create_artifacts:
        description: 'Upload build artifacts'
        type: boolean
        default: true

jobs:
  manual-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: |
          npm run lint
          npm run type-check
          npm test

      - name: Build extension packages
        run: npm run pack

      - name: Show build results
        run: |
          echo "✅ Build completed successfully!"
          echo "📦 Generated packages:"
          find release/ -name "*.zip" -type f -exec echo "  - {}" \; 2>/dev/null || echo "  No packages found"

          echo ""
          echo "📊 Build artifacts:"
          du -sh build/ 2>/dev/null || echo "  Build directory not found"
          du -sh release/ 2>/dev/null || echo "  Release directory not found"

      - name: Upload build artifacts
        if: ${{ inputs.create_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: manual-build-${{ github.run_number }}
          path: |
            release/
            build/
          retention-days: 7

      - name: Summary
        run: |
          echo "## 🚀 Manual Build Completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tests Run:** ${{ inputs.run_tests }}" >> $GITHUB_STEP_SUMMARY
          echo "**Artifacts Created:** ${{ inputs.create_artifacts }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "- Download artifacts to test the extension locally" >> $GITHUB_STEP_SUMMARY
          echo "- Use the 'Release' workflow to create tagged releases" >> $GITHUB_STEP_SUMMARY
          echo "- Check the CI workflow for automated testing on PRs" >> $GITHUB_STEP_SUMMARY
