name: CI

on:
  workflow_dispatch:
    inputs:
      create_artifacts:
        description: 'Create and upload build artifacts'
        required: false
        default: true
        type: boolean
  # push:
  #   branches: [master]
  #   paths:
  #     - 'src/**'
  # pull_request:
  #   branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run pack

      - name: Upload build artifacts
        if: ${{ inputs.create_artifacts || github.event_name != 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: extension-builds-${{ github.sha }}
          path: release/
          retention-days: 7
